import paho.mqtt.client as mqtt

# MQTT broker details...
broker = '127.0.0.1'  #IP for broker...
port = 1883 #Default MQTT Port...
topic = "CSC8112"  # Topic for PM2.5 data...

# Define the callback function for connection event...
def on_connect(client, userdata, flags, rc):
    if rc == 0:
        print("Connected to MQTT Broker, listening for data messages...")
        client.subscribe(topic) # Subscribe to the topic after connecting...
    else:
        print("Failed to connect, return code %d\n", rc) # Return a return code if failed...

#Callback function for receiving messages...
def on_message(client, userdata, msg):

    print(f"Receiving data from MQTT topic: {msg.topic}: {msg.payload.decode()}")

# Initialize the MQTT client...
client = mqtt.Client()

# Assign the callback functions...
client.on_connect = on_connect
client.on_message = on_message

# Connect to the MQTT broker...
client.connect(broker, port, 60)

# Start the MQTT client loop to listen for messages...
client.loop_forever()
